<a href="https://colab.research.google.com/github/hakimaet11-creator/HW01/blob/main/Assignment_7_Data_Preprocessing_and_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/skill_morph/Housing.csv')

In [ ]:
#TODO:How many houses are there?
print(f"Number of houses: {len(df)}")
#Show first 3 houses
df.head(3)

Number of houses: 545

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

In [ ]:
# TODO: Show all column names
print("Columns:")
df.columns

Columns:

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
# TODO: Show data types of columns
print("Data types:")
df.dtypes

Data types:

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

Label Encoding

In [ ]:
#Convert Yes/No to 1/0
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Convert 'mainroad' column
df['mainroad_encoded'] = label_encoder.fit_transform(df['mainroad'])
print("\nAfter Label Encoding 'mainroad':")
print(df[['mainroad', 'mainroad_encoded']])

# Convert 'guestroom' column
df['guestroom_encoded'] = label_encoder.fit_transform(df['guestroom'])
print("\nAfter Label Encoding 'guestroom':")
print(df[['guestroom', 'guestroom_encoded']])

# Convert 'basement' column
df['basement_encoded'] = label_encoder.fit_transform(df['basement'])
print("\nAfter Label Encoding 'basement':")
print(df[['basement', 'basement_encoded']])
# Convert 'hotwaterheating' column
df['hotwaterheating_encoded'] = label_encoder.fit_transform(df['hotwaterheating'])
print("\nAfter Label Encoding 'hotwaterheating':")
print(df[['hotwaterheating', 'hotwaterheating_encoded']])

# Convert 'airconditioning' column
df['airconditioning_encoded'] = label_encoder.fit_transform(df['airconditioning'])
print("\nAfter Label Encoding 'airconditioning':")
print(df[['airconditioning', 'airconditioning_encoded']])

# Convert 'prefarea' column
df['prefarea_encoded'] = label_encoder.fit_transform(df['prefarea'])
print("\nAfter Label Encoding 'prefarea':")
print(df[['prefarea', 'prefarea_encoded']])

# Convert 'furnishingstatus' column
df['furnishingstatus_encoded'] = label_encoder.fit_transform(df['furnishingstatus'])
print("\nAfter Label Encoding 'furnishingstatus':")
print(df[['furnishingstatus', 'furnishingstatus_encoded']])

After Label Encoding 'mainroad':
    mainroad  mainroad_encoded
0        yes                 1
1        yes                 1
2        yes                 1
3        yes                 1
4        yes                 1
..       ...               ...
540      yes                 1
541       no                 0
542      yes                 1
543       no                 0
544      yes                 1

[545 rows x 2 columns]

After Label Encoding 'guestroom':
    guestroom  guestroom_encoded
0          no                  0
1          no                  0
2          no                  0
3          no                  0
4         yes                  1
..        ...                ...
540        no                  0
541        no                  0
542        no                  0
543        no                  0
544        no                  0

[545 rows x 2 columns]

After Label Encoding 'basement':
    basement  basement_encoded
0         no                 0
1         no                 0
2        yes                 1
3        yes                 1
4        yes                 1
..       ...               ...
540      yes                 1
541       no                 0
542       no                 0
543       no                 0
544       no                 0

[545 rows x 2 columns]

After Label Encoding 'hotwaterheating':
    hotwaterheating  hotwaterheating_encoded
0                no                        0
1                no                        0
2                no                        0
3                no                        0
4                no                        0
..              ...                      ...
540              no                        0
541              no                        0
542              no                        0
543              no                        0
544              no                        0

[545 rows x 2 columns]

After Label Encoding 'airconditioning':
    airconditioning  airconditioning_encoded
0               yes                        1
1               yes                        1
2                no                        0
3               yes                        1
4               yes                        1
..              ...                      ...
540              no                        0
541              no                        0
542              no                        0
543              no                        0
544              no                        0

[545 rows x 2 columns]

After Label Encoding 'prefarea':
    prefarea  prefarea_encoded
0        yes                 1
1         no                 0
2        yes                 1
3        yes                 1
4         no                 0
..       ...               ...
540       no                 0
541       no                 0
542       no                 0
543       no                 0
544       no                 0

[545 rows x 2 columns]

After Label Encoding 'furnishingstatus':
    furnishingstatus  furnishingstatus_encoded
0          furnished                         0
1          furnished                         0
2     semi-furnished                         1
3          furnished                         0
4          furnished                         0
..               ...                       ...
540      unfurnished                         2
541   semi-furnished                         1
542      unfurnished                         2
543        furnished                         0
544      unfurnished                         2

[545 rows x 2 columns]

After Label Encoding 'hotwaterheating':
    hotwaterheating  hotwaterheating_encoded
0                no                        0
1                no                        0
2                no                        0
3                no                        0
4                no                        0
..              ...                      ...
540              no                        0
541              no                        0
542              no                        0
543              no                        0
544              no                        0

[545 rows x 2 columns]

After Label Encoding 'airconditioning':
    airconditioning  airconditioning_encoded
0               yes                        1
1               yes                        1
2                no                        0
3               yes                        1
4               yes                        1
..              ...                      ...
540              no                        0
541              no                        0
542              no                        0
543              no                        0
544              no                        0

[545 rows x 2 columns]

After Label Encoding 'prefarea':
    prefarea  prefarea_encoded
0        yes                 1
1         no                 0
2        yes                 1
3        yes                 1
4         no                 0
..       ...               ...
540       no                 0
541       no                 0
542       no                 0
543       no                 0
544       no                 0

[545 rows x 2 columns]

After Label Encoding 'furnishingstatus':
    furnishingstatus  furnishingstatus_encoded
0          furnished                         0
1          furnished                         0
2     semi-furnished                         1
3          furnished                         0
4          furnished                         0
..               ...                       ...
540      unfurnished                         2
541   semi-furnished                         1
542      unfurnished                         2
543        furnished                         0
544      unfurnished                         2

[545 rows x 2 columns]

In [ ]:
print("Current mainroad values:\n",df['mainroad_encoded'].head())

Current mainroad values:
 0    1
1    1
2    1
3    1
4    1
Name: mainroad_encoded, dtype: int64

In [ ]:
# Split into Train and Test
# TODO: Split - 80% train, 20% test
# Separate input (X) and output (y)
#X = df.drop('price', axis=1)  # Everything except price
#y = df['price']                # Only price
numeric_cols = ['area','bedrooms','bathrooms','stories','parking']
encoded_cols = ['mainroad_encoded', 'guestroom_encoded', 'basement_encoded',
                'hotwaterheating_encoded', 'airconditioning_encoded',
                'prefarea_encoded', 'furnishingstatus_encoded']

X = df[numeric_cols + encoded_cols]
y = df['price']


print("X has all housing information (12 columns)")
print("y has house price in Taka (1 column)")

# Split: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=20
)

print(f"\nWe will train with: {len(X_train)} house")
print(f"We will test with: {len(X_test)} house")

X has all housing information (12 columns)
y has house price in Taka (1 column)

We will train with: 436 house
We will test with: 109 house

Apply StandardScaler

In [ ]:
# Area is huge (1650-13300), Bedrooms is small (1-6)!
from sklearn.preprocessing import StandardScaler

numeric_cols = ['area','bedrooms','bathrooms','stories','parking']

scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# scale only numeric columns
X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)
print("✅ Model trained!")

train_score = model.score(X_train_scaled, y_train)
print(f"Training accuracy: {train_score:.1%}")

test_score = model.score(X_test_scaled, y_test)
print(f"Test accuracy: {test_score:.1%}")

✅ Model trained!
Training accuracy: 26.8%
Test accuracy: 1.8%

Save Everything

In [ ]:
import joblib

# Save the model
joblib.dump(model, 'housing_model.pkl')
print("✅ Model saved as 'housing_model.pkl'")

# Save the scaler
joblib.dump(scaler, 'housing_scaler.pkl')
print("✅ Scaler saved as 'housing_scaler.pkl'")

# Save scaled data as CSV
pd.DataFrame(X_train_scaled).to_csv('housing_train_data_scaled.csv', index=False)
print("✅ Scaled data saved as 'housing_train_data_scaled.csv'")

✅ Model saved as 'housing_model.pkl'
✅ Scaler saved as 'housing_scaler.pkl'
✅ Scaled data saved as 'housing_train_data_scaled.csv'

# Predict a House Price

In [ ]:
# New house details:
# area=5000, bedrooms=3, bathrooms=2, stories=2,
# mainroad=yes, guestroom=no, basement=yes,
# hotwaterheating=no, airconditioning=yes,
# parking=2, prefarea=yes, furnishingstatus=furnished


# Load saved model and scaler
model = joblib.load('housing_model.pkl')
scaler = joblib.load('housing_scaler.pkl')

# New house data (12 features)
print("\nNew House information:")
new_house = [[5000, 3, 2, 2,2,1,0,1,0,1,1,0]]
print("Area: 5000")
print("Bedrooms:3")
print("bathrooms:2")
print("stories:2")
print("(mainroad:1")
print("(guestroom:0")
print("(basement:1")
print("(hotwaterheating:0")
print("(airconditioning:1")
print("parking:2")
print("(prefarea:1")
print("(furnishingstatus:0)")

# numeric columns index (first 5)
numeric_idx = [0,1,2,3,4]

# convert to numpy array
new_house_arr = np.array(new_house, dtype=float)

# scale only numeric columns
new_house_arr[:, numeric_idx] = scaler.transform(new_house_arr[:, numeric_idx])

# Make prediction
prediction = model.predict(new_house_arr)

print(f"\nPredicted house price: {prediction[0]:.2f} Taka")

New House information:
Area: 5000
Bedrooms:3
bathrooms:2
stories:2
(mainroad:1
(guestroom:0
(basement:1
(hotwaterheating:0
(airconditioning:1
parking:2
(prefarea:1
(furnishingstatus:0)

Predicted house price: 6300000.00 Taka